version: '3'
services:
  fakemail:
    image: rnwood/smtp4dev
    ports:
      - 3000:80
      - 2525:25
  seq:
    image: datalust/seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
